### ISSUE TITLE
[Bug] Certain Symbols Break Tag Rendering

### ISSUE THREAD

**Issue by Signynt** [mcndt/obsidian-note-sharing#6]
It seems `ü` and `-` among others break the rendering of tags:

![image](https://user-images.githubusercontent.com/67801159/183486447-3398bf80-f4d5-40c4-a1e6-3a416c56883b.png)

Text in the picture:

```md
> [!metadata]-
> - *status*:: draft
> - *source*:: [[2022-04-25 Pathologie Vorlesung]]
> - *tags*:: #krankheitsbild/entzündung #anatomie/darm 
> - *course*:: [[Pathologie]]
> - *review*:: #review/semester-5/pathologie 

### Epidemiologie
```

**Comment by mcndt** [comment]
Thank you for the bug report! Can you recreate the report in this repo: https://github.com/mcndt/noteshare.space

This repo is specifically for the Obsidian plugin. The web app is in a different spot (sorry for the confusion!)

**Comment by mcndt** [comment]
I reposted your report in the correct repo: https://github.com/mcndt/noteshare.space/issues/10

I'll be closing this issue for now. Please follow the issue there for progress reports :)
